import { useCallback, useRef, useState } from "react";

import type { Tone } from "../../types";

export interface DraftFile {
  name: string;
  size: string;
  /** Where the file came from, when it was not the user who picked it. */
  note?: string;
}

interface SuggestionDraft {
  readonly body: string;
  readonly attach?: DraftFile;
}

/** What a suggestion writes into an empty draft. */
export const suggestionDrafts: ReadonlyMap<string, SuggestionDraft> = new Map([
  [
    "Send revised quote",
    {
      body: "Hi Dana,\n\nRevised quote attached — 140 seats, rate locked for 24 months. Everything else is unchanged from v2.\n\nLambert",
      attach: {
        name: "Acme_Renewal_Quote_v3.pdf",
        size: "212 KB",
        note: "regenerated by Deal Desk",
      },
    },
  ],
  [
    "Confirm 24-month term",
    {
      body: "Hi Dana,\n\nConfirmed — we can hold the rate for 24 months. I'll get that reflected in the paperwork.\n\nLambert",
    },
  ],
  [
    "Ask about the board date",
    {
      body: "Hi Dana,\n\nBefore I revise the quote — is the board meeting still the 28th?\n\nLambert",
    },
  ],
]);

export interface Suggestion {
  label: string;
  plugin: { tone: Tone };
}

/** A stand-in for the file picker, so the attachment states stay reachable. */
export const sampleFile: DraftFile = { name: "Acme_Renewal_Quote_v3.pdf", size: "212 KB" };

/**
 * Everything about the draft that is not its text. The text lives in the
 * editor's own state, so there is no second copy of it to keep in step.
 */
export function useDraft() {
  const [attachments, setAttachments] = useState<DraftFile[]>([]);
  const [cc, setCc] = useState(false);
  const [bcc, setBcc] = useState(false);

  const attach = useCallback((files: DraftFile[]) => {
    setAttachments((current) => {
      const known = new Set(current.map((file) => file.name));
      return [...current, ...files.filter((file) => !known.has(file.name))];
    });
  }, []);

  const detach = useCallback((name: string) => {
    setAttachments((current) => current.filter((file) => file.name !== name));
  }, []);

  const reset = useCallback(() => {
    setAttachments([]);
    setCc(false);
    setBcc(false);
  }, []);

  return { attachments, attach, detach, cc, setCc, bcc, setBcc, reset };
}

export type Draft = ReturnType<typeof useDraft>;

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

/**
 * Drag state for a whole composer surface. `dragenter` and `dragleave` fire
 * again for every child the pointer crosses, so the depth counter is the only
 * thing keeping the overlay from strobing as you move across the card.
 */
export function useDropzone(onFiles: (files: DraftFile[]) => void) {
  const depth = useRef(0);
  const [over, setOver] = useState(false);

  const dropProps = {
    onDragEnter: (event: React.DragEvent) => {
      if (!event.dataTransfer.types.includes("Files")) return;
      event.preventDefault();
      depth.current += 1;
      setOver(true);
    },
    onDragOver: (event: React.DragEvent) => {
      if (event.dataTransfer.types.includes("Files")) event.preventDefault();
    },
    onDragLeave: () => {
      depth.current = Math.max(0, depth.current - 1);
      if (depth.current === 0) setOver(false);
    },
    onDrop: (event: React.DragEvent) => {
      event.preventDefault();
      depth.current = 0;
      setOver(false);
      onFiles(
        Array.from(event.dataTransfer.files).map((file) => ({
          name: file.name,
          size: formatSize(file.size),
        })),
      );
    },
  };

  return { over, dropProps };
}
