import {
  AccountId,
  AttachmentId,
  EmailAddress,
  Address,
  MailboxId,
  MessageId,
  ThreadId,
} from "@mosaic/contracts/backend/mail";
import * as DateTime from "effect/DateTime";
import * as Schema from "effect/Schema";

import { StoredAccount } from "./Services/Accounts.ts";
import { StoredMailbox } from "./Services/Mailboxes.ts";
import {
  StoredAttachment,
  StoredMailMessage,
  StoredThread,
  UntrustedHtml,
} from "./Services/Threads.ts";

export const MailFixture = Schema.Struct({
  accounts: Schema.Array(StoredAccount),
  mailboxes: Schema.Array(StoredMailbox),
  threads: Schema.Array(StoredThread),
  messages: Schema.Array(StoredMailMessage),
});
export type MailFixture = typeof MailFixture.Type;

const utcTimestamp = DateTime.makeUnsafe;
const lambert = Address.make({
  name: "Lambert",
  address: EmailAddress.make("lambert@example.com"),
});

export const fixtureIds = {
  accounts: {
    gmail: AccountId.make("account-gmail"),
    microsoft: AccountId.make("account-microsoft"),
    imap: AccountId.make("account-imap"),
  },
  mailboxes: {
    gmailInbox: MailboxId.make("mailbox-gmail-inbox"),
    gmailSent: MailboxId.make("mailbox-gmail-sent"),
    gmailWork: MailboxId.make("mailbox-gmail-work"),
    microsoftInbox: MailboxId.make("mailbox-microsoft-inbox"),
    microsoftSent: MailboxId.make("mailbox-microsoft-sent"),
    microsoftArchive: MailboxId.make("mailbox-microsoft-archive"),
    imapInbox: MailboxId.make("mailbox-imap-inbox"),
    imapSent: MailboxId.make("mailbox-imap-sent"),
    imapProjects: MailboxId.make("mailbox-imap-projects"),
  },
  threads: {
    annualReport: ThreadId.make("thread-gmail-annual-report"),
    designReview: ThreadId.make("thread-microsoft-design-review"),
    migration: ThreadId.make("thread-imap-migration"),
    newsletter: ThreadId.make("thread-imap-newsletter"),
  },
  messages: {
    annualReportRequest: MessageId.make("message-gmail-annual-report-request"),
    annualReportReply: MessageId.make("message-gmail-annual-report-reply"),
    designReview: MessageId.make("message-microsoft-design-review"),
    migrationPlan: MessageId.make("message-imap-migration-plan"),
    migrationReply: MessageId.make("message-imap-migration-reply"),
    newsletter: MessageId.make("message-imap-newsletter"),
  },
} as const;

const accounts = [
  StoredAccount.make({
    id: fixtureIds.accounts.gmail,
    providerKind: "gmail",
    providerAccountId: "118208422804124894995",
    displayName: "Personal Gmail",
    emailAddress: lambert.address,
    createdAt: utcTimestamp("2026-08-01T08:00:00.000Z"),
    updatedAt: utcTimestamp("2026-08-12T18:00:00.000Z"),
  }),
  StoredAccount.make({
    id: fixtureIds.accounts.microsoft,
    providerKind: "microsoft-graph",
    providerAccountId: "c555f57b-1e45-4aeb-9dc2-9d4f2d240c1f",
    displayName: "Mosaic Work",
    emailAddress: EmailAddress.make("lambert@mosaic.test"),
    createdAt: utcTimestamp("2026-08-01T08:10:00.000Z"),
    updatedAt: utcTimestamp("2026-08-12T18:05:00.000Z"),
  }),
  StoredAccount.make({
    id: fixtureIds.accounts.imap,
    providerKind: "imap",
    providerAccountId: "lambert@fastmail.test",
    displayName: "Fastmail",
    emailAddress: EmailAddress.make("lambert@fastmail.test"),
    createdAt: utcTimestamp("2026-08-01T08:20:00.000Z"),
    updatedAt: utcTimestamp("2026-08-12T18:10:00.000Z"),
  }),
];

const mailboxes = [
  StoredMailbox.make({
    id: fixtureIds.mailboxes.gmailInbox,
    accountId: fixtureIds.accounts.gmail,
    providerMailboxId: "INBOX",
    name: "Inbox",
    kind: "label",
    role: "inbox",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.gmailSent,
    accountId: fixtureIds.accounts.gmail,
    providerMailboxId: "SENT",
    name: "Sent",
    kind: "label",
    role: "sent",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.gmailWork,
    accountId: fixtureIds.accounts.gmail,
    providerMailboxId: "Label_42",
    name: "Work",
    kind: "label",
    role: null,
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.microsoftInbox,
    accountId: fixtureIds.accounts.microsoft,
    providerMailboxId: "AQMkADAwATM0MDAAMS0wMAItMDAKAEYAAAAA",
    name: "Inbox",
    kind: "folder",
    role: "inbox",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.microsoftSent,
    accountId: fixtureIds.accounts.microsoft,
    providerMailboxId: "AQMkADAwATM0MDAAMS0wMAItMDAKAEYBBBBB",
    name: "Sent Items",
    kind: "folder",
    role: "sent",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.microsoftArchive,
    accountId: fixtureIds.accounts.microsoft,
    providerMailboxId: "AQMkADAwATM0MDAAMS0wMAItMDAKAEYCCCCC",
    name: "Archive",
    kind: "folder",
    role: "archive",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.imapInbox,
    accountId: fixtureIds.accounts.imap,
    providerMailboxId: "INBOX",
    name: "Inbox",
    kind: "folder",
    role: "inbox",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.imapSent,
    accountId: fixtureIds.accounts.imap,
    providerMailboxId: "Sent",
    name: "Sent",
    kind: "folder",
    role: "sent",
    parentId: null,
  }),
  StoredMailbox.make({
    id: fixtureIds.mailboxes.imapProjects,
    accountId: fixtureIds.accounts.imap,
    providerMailboxId: "Projects/Mosaic",
    name: "Mosaic",
    kind: "folder",
    role: null,
    parentId: null,
  }),
];

const threads = [
  StoredThread.make({
    id: fixtureIds.threads.annualReport,
    accountId: fixtureIds.accounts.gmail,
    providerThreadId: "gmail-thread-1842",
    threadingKind: "provider",
    subject: "Q3 annual report",
    createdAt: utcTimestamp("2026-08-10T08:30:00.000Z"),
    updatedAt: utcTimestamp("2026-08-10T10:15:00.000Z"),
  }),
  StoredThread.make({
    id: fixtureIds.threads.designReview,
    accountId: fixtureIds.accounts.microsoft,
    providerThreadId: "AAQkAGQ5M2Q1YTI3LTc4ZjAtNDc0ZC1hYw==",
    threadingKind: "provider",
    subject: "Desktop navigation review",
    createdAt: utcTimestamp("2026-08-11T13:00:00.000Z"),
    updatedAt: utcTimestamp("2026-08-11T13:00:00.000Z"),
  }),
  StoredThread.make({
    id: fixtureIds.threads.migration,
    accountId: fixtureIds.accounts.imap,
    providerThreadId: null,
    threadingKind: "headers",
    subject: "SQLite migration plan",
    createdAt: utcTimestamp("2026-08-12T07:45:00.000Z"),
    updatedAt: utcTimestamp("2026-08-12T09:20:00.000Z"),
  }),
  StoredThread.make({
    id: fixtureIds.threads.newsletter,
    accountId: fixtureIds.accounts.imap,
    providerThreadId: null,
    threadingKind: "singleton",
    subject: "The local-first dispatch",
    createdAt: utcTimestamp("2026-08-09T06:00:00.000Z"),
    updatedAt: utcTimestamp("2026-08-09T06:00:00.000Z"),
  }),
];

const messages = [
  StoredMailMessage.make({
    id: fixtureIds.messages.annualReportRequest,
    accountId: fixtureIds.accounts.gmail,
    threadId: fixtureIds.threads.annualReport,
    providerMessageId: "gmail-message-1842-1",
    internetMessageId: "<annual-report-1@northstar.test>",
    inReplyTo: null,
    references: [],
    subject: "Q3 annual report",
    sentAt: utcTimestamp("2026-08-10T08:29:00.000Z"),
    receivedAt: utcTimestamp("2026-08-10T08:30:00.000Z"),
    from: Address.make({
      name: "Ava Chen",
      address: EmailAddress.make("ava@northstar.test"),
    }),
    replyTo: [],
    to: [lambert],
    cc: [],
    bcc: [],
    preview: "Could you review the Mosaic section before Friday?",
    body: {
      text: "Hi Lambert, could you review the Mosaic section of the Q3 annual report before Friday?",
      html: UntrustedHtml.make(
        '<p>Hi Lambert, could you review the <strong>Mosaic</strong> section before Friday?</p><script>alert("fixture")</script><img src="https://tracking.test/pixel" onerror="alert(1)">',
      ),
    },
    isRead: false,
    isStarred: true,
    isImportant: true,
    isDraft: false,
    rawMessageBlobHash: null,
    mailboxIds: [fixtureIds.mailboxes.gmailInbox, fixtureIds.mailboxes.gmailWork],
    attachments: [
      StoredAttachment.make({
        id: AttachmentId.make("attachment-annual-report"),
        messageId: fixtureIds.messages.annualReportRequest,
        providerAttachmentId: "gmail-attachment-77",
        filename: "q3-annual-report.pdf",
        mediaType: "application/pdf",
        sizeBytes: 482_320,
        contentId: null,
        disposition: "attachment",
        blobHash: null,
      }),
    ],
  }),
  StoredMailMessage.make({
    id: fixtureIds.messages.annualReportReply,
    accountId: fixtureIds.accounts.gmail,
    threadId: fixtureIds.threads.annualReport,
    providerMessageId: "gmail-message-1842-2",
    internetMessageId: "<annual-report-2@example.com>",
    inReplyTo: "<annual-report-1@northstar.test>",
    references: ["<annual-report-1@northstar.test>"],
    subject: "Re: Q3 annual report",
    sentAt: utcTimestamp("2026-08-10T10:15:00.000Z"),
    receivedAt: utcTimestamp("2026-08-10T10:15:00.000Z"),
    from: lambert,
    replyTo: [],
    to: [
      Address.make({
        name: "Ava Chen",
        address: EmailAddress.make("ava@northstar.test"),
      }),
    ],
    cc: [],
    bcc: [],
    preview: "Reviewed. I left two comments on the Mosaic section.",
    body: {
      text: "Reviewed. I left two comments on the Mosaic section. The numbers look solid.",
      html: UntrustedHtml.make(
        "<p>Reviewed. I left two comments on the <strong>Mosaic</strong> section.</p>",
      ),
    },
    isRead: true,
    isStarred: false,
    isImportant: false,
    isDraft: false,
    rawMessageBlobHash: null,
    mailboxIds: [fixtureIds.mailboxes.gmailSent, fixtureIds.mailboxes.gmailWork],
    attachments: [],
  }),
  StoredMailMessage.make({
    id: fixtureIds.messages.designReview,
    accountId: fixtureIds.accounts.microsoft,
    threadId: fixtureIds.threads.designReview,
    providerMessageId: "AAMkAGQ5M2Q1YTI3LTc4ZjAtNDc0ZC1hYwBGAAAA",
    internetMessageId: "<design-review@mosaic.test>",
    inReplyTo: null,
    references: [],
    subject: "Desktop navigation review",
    sentAt: utcTimestamp("2026-08-11T12:58:00.000Z"),
    receivedAt: utcTimestamp("2026-08-11T13:00:00.000Z"),
    from: Address.make({
      name: "Mira Patel",
      address: EmailAddress.make("mira@mosaic.test"),
    }),
    replyTo: [],
    to: [
      Address.make({
        name: "Lambert",
        address: EmailAddress.make("lambert@mosaic.test"),
      }),
    ],
    cc: [
      Address.make({
        name: "Product",
        address: EmailAddress.make("product@mosaic.test"),
      }),
    ],
    bcc: [],
    preview: "The simplified navigation prototype is ready for review.",
    body: {
      text: "The simplified navigation prototype is ready. Please focus on keyboard flow and density.",
      html: UntrustedHtml.make(
        '<p>The simplified navigation prototype is ready.</p><a href="javascript:alert(1)">Open prototype</a>',
      ),
    },
    isRead: false,
    isStarred: false,
    isImportant: true,
    isDraft: false,
    rawMessageBlobHash: null,
    mailboxIds: [fixtureIds.mailboxes.microsoftInbox],
    attachments: [
      StoredAttachment.make({
        id: AttachmentId.make("attachment-navigation-inline"),
        messageId: fixtureIds.messages.designReview,
        providerAttachmentId: "graph-attachment-4",
        filename: "navigation.png",
        mediaType: "image/png",
        sizeBytes: 92_410,
        contentId: "navigation-preview@mosaic.test",
        disposition: "inline",
        blobHash: null,
      }),
    ],
  }),
  StoredMailMessage.make({
    id: fixtureIds.messages.migrationPlan,
    accountId: fixtureIds.accounts.imap,
    threadId: fixtureIds.threads.migration,
    providerMessageId: "imap-uid-188",
    internetMessageId: "<sqlite-migration-1@atelier.test>",
    inReplyTo: null,
    references: [],
    subject: "SQLite migration plan",
    sentAt: utcTimestamp("2026-08-12T07:43:00.000Z"),
    receivedAt: utcTimestamp("2026-08-12T07:45:00.000Z"),
    from: Address.make({
      name: "Noah Williams",
      address: EmailAddress.make("noah@atelier.test"),
    }),
    replyTo: [],
    to: [
      Address.make({
        name: "Lambert",
        address: EmailAddress.make("lambert@fastmail.test"),
      }),
    ],
    cc: [],
    bcc: [],
    preview: "The migration should keep mail and FTS changes in one transaction.",
    body: {
      text: "The SQLite migration should keep normalized mail records and FTS changes in one transaction.",
      html: UntrustedHtml.make(
        "<p>The SQLite <em>migration</em> should keep mail and FTS changes in one transaction.</p>",
      ),
    },
    isRead: true,
    isStarred: false,
    isImportant: false,
    isDraft: false,
    rawMessageBlobHash: null,
    mailboxIds: [fixtureIds.mailboxes.imapInbox, fixtureIds.mailboxes.imapProjects],
    attachments: [],
  }),
  StoredMailMessage.make({
    id: fixtureIds.messages.migrationReply,
    accountId: fixtureIds.accounts.imap,
    threadId: fixtureIds.threads.migration,
    providerMessageId: "imap-uid-192",
    internetMessageId: "<sqlite-migration-2@fastmail.test>",
    inReplyTo: "<sqlite-migration-1@atelier.test>",
    references: ["<sqlite-migration-1@atelier.test>"],
    subject: "Re: SQLite migration plan",
    sentAt: utcTimestamp("2026-08-12T09:20:00.000Z"),
    receivedAt: utcTimestamp("2026-08-12T09:20:00.000Z"),
    from: Address.make({
      name: "Lambert",
      address: EmailAddress.make("lambert@fastmail.test"),
    }),
    replyTo: [],
    to: [
      Address.make({
        name: "Noah Williams",
        address: EmailAddress.make("noah@atelier.test"),
      }),
    ],
    cc: [],
    bcc: [],
    preview: "Agreed. The migration and search index should commit atomically.",
    body: {
      text: "Agreed. The migration and search index should commit atomically, with fixtures proving the path.",
      html: UntrustedHtml.make(
        "<p>Agreed. The migration and search index should commit atomically.</p>",
      ),
    },
    isRead: true,
    isStarred: true,
    isImportant: false,
    isDraft: false,
    rawMessageBlobHash: null,
    mailboxIds: [fixtureIds.mailboxes.imapSent, fixtureIds.mailboxes.imapProjects],
    attachments: [],
  }),
  StoredMailMessage.make({
    id: fixtureIds.messages.newsletter,
    accountId: fixtureIds.accounts.imap,
    threadId: fixtureIds.threads.newsletter,
    providerMessageId: "imap-uid-174",
    internetMessageId: "<dispatch-41@localfirst.test>",
    inReplyTo: null,
    references: [],
    subject: "The local-first dispatch",
    sentAt: utcTimestamp("2026-08-09T05:58:00.000Z"),
    receivedAt: utcTimestamp("2026-08-09T06:00:00.000Z"),
    from: Address.make({
      name: "Local First",
      address: EmailAddress.make("dispatch@localfirst.test"),
    }),
    replyTo: [],
    to: [
      Address.make({
        name: null,
        address: EmailAddress.make("lambert@fastmail.test"),
      }),
    ],
    cc: [],
    bcc: [],
    preview: "This week: durable local search and calm offline software.",
    body: {
      text: null,
      html: UntrustedHtml.make(
        "<h1>The local-first dispatch</h1><p>Durable local search, calm offline software, and better ownership boundaries.</p>",
      ),
    },
    isRead: true,
    isStarred: false,
    isImportant: false,
    isDraft: false,
    rawMessageBlobHash: null,
    mailboxIds: [fixtureIds.mailboxes.imapInbox],
    attachments: [],
  }),
];

export const mailFixture = MailFixture.make({ accounts, mailboxes, threads, messages });
